---
- name: Clone the repo
  ansible.builtin.git:
    repo: '{{ project.repo_url }}'
    dest: '{{ project.dest }}'
    version: '{{ project.branch }}'

- name: Apply snippets
  ansible.builtin.get_url:
    url: '{{ snippet.value }}'
    dest: '{{ snippet.key }}'
    owner: '{{ dev_user_name }}'
    group: '{{ dev_user_name }}'
    mode: u=rw,g=,o=
  with_dict: '{{ project.snippets }}'
  loop_control:
    loop_var: snippet
  when: project.snippets is defined and project.snippets
