---
- name: Recreate the devenv
  hosts: localhost
  vars_files:
    - vars/devlab-pve.yml
    - vaults/vault.yml
    - vars/dashy-dev.yml
  roles:
    - role: pve_purge
      when: recreate is defined and recreate
    - role: pve_lxc_create
      when: recreate is defined and recreate

- name: Configure the devenv
  hosts: dashy_dev
  vars_files:
    - vaults/vault.yml
    - vars/dashy-dev.yml
  roles:
    - role: base
      when: recreate is defined and recreate

- name: Make it a node.js devenv
  hosts: dashy_dev
  vars_files:
    - vaults/vault.yml
    - vars/dashy-dev.yml
  roles:
    - role: nvm
      vars:
        ansible_user: '{{ dev_user_name }}'
