- name: Recreate the host
  hosts: localhost
  vars_files:
    - vars/devlab-pve.yml
    - vaults/vault.yml
    - vars/docker.yml
  roles:
    - pve_purge
    - pve_lxc_create

- name: Configure the devenv
  hosts: docker
  vars_files:
    - vaults/vault.yml
    - vars/docker.yml
  roles:
    - base
    - docker
