---
- name: "Create GitLab Group"
  community.general.gitlab_group:
    api_url: '{{ gitlab_url }}'
    api_username: root
    api_password: '{{ gitlab_root_password }}'
    name: '{{ item.name }}'
    path: '{{ item.path }}'
    visibility: '{{ item.visibility }}'
    project_creation_level: maintainer
    state: present
    ca_path: '/usr/local/share/ca-certificates/devlab_ca.pem'
  loop: '{{ gitlab_groups }}'

- name: "Create GitLab User"
  community.general.gitlab_user:
    api_url: '{{ gitlab_url }}'
    api_username: root
    api_password: '{{ gitlab_root_password }}'
    name: '{{ gitlab_user_name }}'
    username: '{{ gitlab_user_name }}'
    password: '{{ gitlab_user_password }}'
    email: devlab@example.com
    state: present
    ca_path: '/usr/local/share/ca-certificates/devlab_ca.pem'

- name: Add the user to all the groups
  community.general.gitlab_group_members:
    api_url: '{{ gitlab_url }}'
    api_username: root
    api_password: '{{ gitlab_root_password }}'
    gitlab_group: '{{ item.path }}'
    gitlab_user: '{{ gitlab_user_name }}'
    access_level: owner
    ca_path: '/usr/local/share/ca-certificates/devlab_ca.pem'
  loop: '{{ gitlab_groups }}'

- name: "Create repositories"
  community.general.gitlab_project:
    api_url: '{{ gitlab_url }}'
    api_username: root
    api_password: '{{ gitlab_root_password }}'
    name: '{{ item.name }}'
    path: '{{ item.path }}'
    group: '{{ item.group }}'
    visibility: '{{ item.visibility }}'
    ca_path: '/usr/local/share/ca-certificates/devlab_ca.pem'
  loop: '{{ gitlab_projects }}'
