---
- name: Configure IPv4 routing
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict:
    # Documentation: https://docs.kernel.org/networking/ip-sysctl.html
    # Enable routing
    net.ipv4.ip_forward: 1
    # SYN-flood protection
    net.ipv4.tcp_syncookies: 1
    net.ipv4.tcp_synack_retries: 3
    # Source validation
    net.ipv4.conf.default.rp_filter: 1
    net.ipv4.conf.all.rp_filter: 1

- name: Copy nftables configuration file
  ansible.builtin.copy:
    src: nftables.conf
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Restart nftables
  ansible.builtin.systemd_service:
    name: nftables
    enabled: true
    state: restarted
