---
- name: Install apache
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
  loop: '{{ lamp_apache2_default_packages + (lamp_apache2_extra_packages | default([])) }}'

- name: Enable apache2 modules
  community.general.apache2_module:
    name: "{{ item }}"
    state: present
  loop: '{{ lamp_apache2_default_modules + (lamp_apache2_extra_modules | default([])) }}'

- name: Create sites
  ansible.builtin.template:
    src: vhost.conf.j2
    dest: '/etc/apache2/sites-available/{{ site.hostname }}.conf'
    owner: www-data
    group: www-data
    mode: u=rw,o=rw,g=r
  loop: '{{ lamp_server_sites }}'
  loop_control:
    loop_var: site
  when: site.document_root is defined and site.document_root

- name: Enable sites
  ansible.builtin.command:
    cmd: a2ensite {{ site.hostname }}
    creates: '/etc/apache2/sites-enabled/{{ site.hostname }}.conf'
  loop: '{{ lamp_server_sites }}'
  loop_control:
    loop_var: site
  when: site.document_root is defined and site.document_root
