- name: Cleanup
  ansible.builtin.file:
    path: '{{ site.install_path }}'
    force: true
    state: absent
  vars:
    ansible_become: true

- name: Install using composer
  ansible.builtin.include_tasks: composer.yml
  when: site.composer_project is defined

- name: Install using downloaded archive
  ansible.builtin.include_tasks: download_archive.yml
  when: site.archive_url is defined

- name: Install using git clone
  ansible.builtin.include_tasks: git_clone.yml
  when: site.git_clone_url is defined

- name: Execute shell commands
  ansible.builtin.raw: 'cd {{ site.install_path }} && {{ site.shell_commands | join(" && ") }}'
  changed_when: true
  when: site.shell_commands is defined and site.shell_commands

- name: Create phpinfo file
  ansible.builtin.copy:
    content: '<?php phpinfo(); ?>'
    dest: '{{ site.document_root }}/php.php'
    owner: '{{ dev_user_name }}'
    group: '{{ dev_user_name }}'
    mode: u=rw,g=r,o=r
