- name: Install required packages
  ansible.builtin.package:
    name: dnf-plugins-core
    state: present

- name: Add the docker repository
  ansible.builtin.command:
    cmd: "dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo"
    creates: /etc/yum.repos.d/docker-ce.repo
