---
- name: Install wireguard packages
  ansible.builtin.package:
    name: '{{ item }}'
  loop:
    - wireguard
    - resolvconf
    - nftables

- name: Copy wireguard configuration
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: '/etc/wireguard/{{ wireguard_router.wg_interface_name }}.conf'
    owner: root
    group: root
    mode: u=rw,g=r,o=

- name: Install the wireguard service
  ansible.builtin.service:
    name: 'wg-quick@{{ wireguard_router.wg_interface_name }}'
    state: restarted
    enabled: true
